#show sql statement
logging.level.org.hibernate.SQL: debug
#show sql values
logging.level.org.hibernate.type.descriptor.sql: trace

spring:
  jpa:
    hibernate:
      ddl-auto: none

spring.h2.console.enabled: true
